name: foundry
on: { workflow_dispatch, push: { branches: [main] } }
jobs:
  build_v2:
    name: foundry
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@master
        with:
          name: wuz
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          upstream-cache: https://wuz.cachix.org
      - run: nix run .#skopeo -- login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - run: nix run .#image.copyToRegistry
      - run: |
          export IMAGE="docker://$(nix eval --raw .#image.imageName)"
          export TAG="$(nix eval --raw .#image.imageTag)"
          skopeo --insecure-policy copy "$IMAGE:$TAG" "$IMAGE:$(date +"%F")"
          skopeo --insecure-policy copy "$IMAGE:$TAG" "$IMAGE:latest"

